- name: create stack
  hosts: localhost
  gather_facts: no
  connection: local
  become: no
  vars_files:
    - stack-nodes.yml
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    public_network_name: public
  roles:
    - ansible-role-os-stack