- name: delete stack
  hosts: localhost
  gather_facts: no
  connection: local
  become: no
  vars_files:
    - stack-nodes.yml
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    ansible_port: 5986
  roles:
    - role: stack-template
      role_action: deprovision