---

- name: check openstack config file
  stat: path="{{ config_file }}"
  register: st
  delegate_to: 127.0.0.1

- name: include openstack details
  include_vars: "{{ config_file }}"
  when: st.stat.exists and st.stat.isreg

- name: delete stack
  os_stack:
    name: "{{ stack_name | default('test_stack') }}"
    state: absent