heat_template_version: 2013-05-23

description: >
  Deploys an instance.

parameters:
  key_name:
    description: Name of an existing keypair to encrypt the Admin password
    type: string

  flavor:
    description: Id or name of an existing flavor
    type: string
    default: m1.medium

  image:
    description: Id or name of an existing Windows image
    type: string

  public_network_id:
    type: string
    description: >
      ID of an existing public network where a floating IP will be
      allocated.

  private_network_id:
    type: string
    description: Id of an existing private network

resources:
  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id }

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on: server_port
    properties:
      floating_network_id: { get_param: public_network_id }
      port_id: { get_resource: server_port }

  wintest:
    type: OS::Nova::Server
    depends_on: [ server_port ]
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_port }
outputs:
  wintest_server_public_ip:
    description: The public IP address
    value: { get_attr: [ server_floating_ip, floating_ip_address ] }